### ISSUE TITLE
Training with MViT for long-term anticipation

### ISSUE THREAD

**Issue by takfate** [EGO4D/forecasting#18]
When I train the baseline with MViT, the error occurs.
```
RuntimeError: unsupported operation: some elements of the input tensor and the written-to tensor refer to a single memory location. Please clone() the tensor before performing the operation.
```
But I can train` slowfast `model successfully.
May I ask where the problem is?

**Comment by takfate** [comment]
@Tushar-N Hello, Can you give me some help?

**Comment by Tushar-N** [comment]
I don't see this error when I run the bottom block of `ego4d_forecasting.sh` for MViT Concat. Could you check to make sure the torch versions match:
```
torch==1.9.0
torchvision==0.10.0
```

It would also help if I could see more of the error trace (which line causes this error?).
