### ISSUE TITLE
new LTA checkpoints

### ISSUE THREAD

**Issue by CeeZh** [EGO4D/forecasting#28]
Hi,

Are the provided LTA checkpoints pretrained on the v1 dataset or v2 dataset? Thanks!

**Comment by Tushar-N** [comment]
Updated on CLI! Use the v2 flag to get the new checkpoints.

**Comment by MiaQiu** [comment]
Hello Tushar,

I tried to download the v2 checkpoints using "python -m ego4d.cli.cli --output_directory="D:/ego4d_data" --datasets lta_models  --benchmarks FHO --version v2"

However got below error:
oto 403 Exception For exists: 6c6d81f0-fda8-45a8-89a1-59f1f5f687f0 | lta_slowfast_trf_v2.ckpt
Missing s3 object (ignored for download): 6c6d81f0-fda8-45a8-89a1-59f1f5f687f0 | lta_slowfast_trf_v2.ckpt 

Could you advise?
Thank you!
Mia
