### ISSUE TITLE
new LTA checkpoints: missing lta_slowfast_trf_v2.ckpt

### ISSUE THREAD

**Issue by MiaQiu** [EGO4D/forecasting#29]
Hello team,

I tried to download the v2 checkpoints using "python -m ego4d.cli.cli --output_directory="D:/ego4d_data" --datasets lta_models --benchmarks FHO --version v2"

However got below error:
oto 403 Exception For exists: 6c6d81f0-fda8-45a8-89a1-59f1f5f687f0 | lta_slowfast_trf_v2.ckpt
Missing s3 object (ignored for download): 6c6d81f0-fda8-45a8-89a1-59f1f5f687f0 | lta_slowfast_trf_v2.ckpt

Could you advise?
Thank you!
Mia

**Comment by Tushar-N** [comment]
@miguelmartin75 Can you check on this issue? I see the checkpoints on S3, but I can't download them either.

**Comment by miguelmartin75** [comment]
Will look at this and other related issues popping up with the CLI for V2.

**Comment by takfate** [comment]
@miguelmartin75 @Tushar-N Hello, we have some questions about the annotations of LTAv2. In the new annotations, an action is later than the other, but the `aciton_Idx` of the former is smaller than the latter. I want to know whether it is legal because a part of out-of-order actions may affect the evaluation of the edit distance and lead to information leaking.

**Comment by Tushar-N** [comment]
Since actions overlap (start/end time), the `action_idx` is based on the PNR frame. These are unique and are ordered correctly for the clips.

**Comment by jinlongbin** [comment]
> Will look at this and other related issues popping up with the CLI for V2.

How can I download lta_models? I still can't download it.

**Comment by shaunak27** [comment]
Hello @miguelmartin75 @Tushar-N 
Did you find a resolution for this issue? I am still unable to download the lta checkpoints and run into the same errors.

**Comment by Annusha** [comment]
same here, cannot download the models

**Comment by miguelmartin75** [comment]
Apologies on the delay here, got pre-occupied with other items. I have updated the CLI, so now:

```
python -m ego4d.cli.cli -o <out-dir> --datasets lta_models --version v2
```

works. Please let me know if you have any further issues.
