### ISSUE TITLE
Whether the LTA action boundary is accessible during testing?

### ISSUE THREAD

**Issue by takfate** [EGO4D/forecasting#30]
During training, I can model each 8s long action by using the start and end of each clip as instances. However, this approach requires known action boundaries. If this method is adopted during testing, obtaining the boundary of each action instance in the observable video is also necessary. I wonder if this way is legal.
If this method is not allowed, maybe every time the future is predicted, all the previous observable videos can only be used. The boundary of each action instance that has occurred cannot be obtained. I wonder if my understanding is correct.

**Comment by Tushar-N** [comment]
The test set annotations are released with boundary information. It is okay to use the segment boundaries, however each prediction (i.e., input 8 clips, output 20 clips) must be independently generated. Methods must not cheat by looking into the future in any way (predictions or temporal segments) to revise past predictions.

We'll clarify this in the challenge instructions before the next edition
