### ISSUE TITLE
Number of training/eval samples in LTA task

### ISSUE THREAD

**Issue by Chuhanxx** [EGO4D/forecasting#31]
Hi, thank you for on the great work on the benchmark.

In long-term action anticipatio, to cover all the action clips with sufficient number of future actions, should the range be
`range(len(video_clips) - num_future_actions - num_input_actions +1)` instead of `range(len(video_clips) - num_future_actions - num_input_actions)` in
https://github.com/EGO4D/forecasting/blob/4a27d4a9a025416350f015046f29e4800a629065/ego4d_forecasting/datasets/ptv_dataset_helper.py#L450

**Comment by Tushar-N** [comment]
Good catch, thanks! We won't change evaluation to stay consistent with the challenge, but extra training samples can't hurt!
