### ISSUE TITLE
"Indument" possible typo in annotations

### ISSUE THREAD

**Issue by RazvanPasca** [EGO4D/forecasting#4]
Hello! I've been looking over the short-term-anticipation data and stumbled across what might be a possible typo in the noun category, namely "indument". From what I've searched there is no such word that might correspond to it in English. Is it a typo and if yes, what is the expected correct label?

The annotation can be found in any of the _fho_sta_train.json_ and _fho_sta_val.json_ for _id_=34.

**Comment by antoninofurnari** [comment]
Hello, thank you for bringing this up. You are right, "indument" is not an English word! That was supposed to be "garment". We will check and see how to update, but for the moment you can consider "garment" as the correct label.

**Comment by RazvanPasca** [comment]
I see, thank you for the update and the great work on the project!

**Comment by antoninofurnari** [comment]
I know there has not been an update in the annotations so far, but this is a somewhat slow process as we want to minimize the number of updates in the annotations. However, I wanted to assure that this (minor) fix is already in the pipeline and will be made public soon!
