### ISSUE TITLE
Sampling of clips for the testing phase

### ISSUE THREAD

**Issue by olga-zats** [EGO4D/forecasting#7]
Hi!

I had a question concerning the sampling procedure of input clips for the lta testing phase. When running the evaluation code, I get the following Debug messages [image](https://user-images.githubusercontent.com/56084320/165524157-193b9ca7-5cd0-4367-8fcb-bfc359d9e222.png). Having looked at the code of the ptv_dataset_helper, I am not sure I completely understand how clips for testing are sampled. From my understanding, the following happens:

In the ptv_dataset_helper, where input clips are sampled, a counter **self._next_clip_start_time** is kept, which keeps track of the time of the last clip sampled from the particular video. During training and validation, since sub-clips from annotated clips are subsampled at random, the parameter **self._next_clip_start_time** is not taken into account. During testing, however, this parameter is added to all the sub-clips which are sampled from the same video. But looking at the way the sequences of the input clips are sampled, I do not see why this counter is required. For example, given clips (i1, i2, i3, i4, i5) from a video v, if we sample 4 clips for the encoder, we get the following input tuples t1 = (i1, i2, i3, i4) and t2 = (i2, i3, i4, i5). If we process t1 before t2 (or t2 before t1 also) and the ending time of clip i4 is greater than the starting time of clip i2 (which is true most of the time), then input clips from t2 won't be loaded correctly. (I add a more concrete example in the photos) 
![image](https://user-images.githubusercontent.com/56084320/165525503-645b5af7-1333-4045-9a6e-dda10f737a3e.png)
![image](https://user-images.githubusercontent.com/56084320/165525517-ee9e03b7-dcdf-4987-8831-641e7f979a11.png)

So, I wonder if I misunderstand something about how clips are sampled or is there a way to ignore this counter?
Thank you for your answer!

**Comment by antoninofurnari** [comment]
Hello, I see this issue is now old, but I guess the author and other readers may still benefit from some clarifications. Maybe @Tushar-N can comment on this issue since it is related to LTA?

**Comment by surisdi** [comment]
Hi, I am also interested in this. Is there any update? Thanks!

**Comment by Tushar-N** [comment]
Sorry for the delay on this, and thanks for your detailed report on the issue.

As you pointed out, the issue stems from the fact that the same clip needs to be loaded for multiple instances, causing an inconsistency with `self._next_clip_start_time`. In short, the start time would go out of the clip bounds, and result in clips being sampled from arbitrary points in the video (but in a deterministic manner). 

The simplest solution to this is always selecting the center clip during testing using a custom sampler like below. The old code was testing with a single view per clip anyway, so this is consistent with the original test loop. 
```
from pytorchvideo.data.clip_sampling import ClipSampler, ClipInfo
from typing import Dict, Any

class CenterClipVideoSampler(ClipSampler):
    """
    Samples just a single clip from the center of the video (use for testing)
    """

    def __init__(
        self, clip_duration: float
    ) -> None:
        super().__init__(clip_duration)

    def __call__(
        self, last_clip_time: float, video_duration: float, annotation: Dict[str, Any]
    ) -> ClipInfo:

        clip_start_sec = video_duration / 2 - self._clip_duration / 2

        return ClipInfo(
            clip_start_sec,
            clip_start_sec + self._clip_duration,
            0,
            0,
            True,
        )
```

and then in the `Ego4dLongTermAnticipation` [class](https://github.com/EGO4D/forecasting/blob/971849a8840ed3c38a81890461cf9f5e37a40b0a/ego4d/datasets/long_term_anticipation.py#L44):
```
if mode == 'test':
    clip_sampler = CenterClipVideoSampler(clip_duration)
```

**Comment by takfate** [comment]
@Tushar-N 
Hello, I have replaced your new codes.
But it seems to have some errors for submitting the `output.json`.
Some keys are missing in the `Stdout file` on the EvalAI website.

```
{'85f21d37-73c8-42e8-bdda-1ff89dd6eb15_8', '7a6cdfe4-db07-4807-a3c7-6faca1ce9be5_30', '366b9e0e-a924-4098-8fd0-c480ab1d4972_29', '43effa66-0aea-46ca-be77-a3498395cbee_178', '515486af-f327-47ca-a1fc-28549f913e47_12', 'aac468fa-eb38-4d85-bf68-20eb452b2d27_21', 'a70e725a-3c7e-45b6-b602-85d48f6752e8_29', 'e2ddee72-8dd1-464e-bad0-ce55d51e75c3_23', '506792a1-a4fe-475e-a358-665150095b81_54', 'a70e725a-3c7e-45b6-b602-85d48f6752e8_97', '21280453-ee88-4271-aa97-a111983bfef9_11', '5eed19de-ab08-4015-980d-8e75fe411094_46', '43effa66-0aea-46ca-be77-a3498395cbee_104', '89422cf4-ffa4-4d3c-b469-6d899f8379da_63', '4a71ef05-d236-46ec-8a4c-8a384a2b1d23_41', 'bbc51aad-3e80-48e8-8338-ee1828ede7b9_41', '814baefc-d043-40f8-bb52-3573266f613f_25', 'b4c14f3c-c8d7-45ba-bad4-d69438eab173_10', 'ccd39504-2a28-4b1c-ad85-d75b3ca622ad_54', '82fe2903-49b0-42f2-b9f5-f8b383ba2a96_29', '675de519-10e4-41ef-965a-6397b4218cdc_46', 'dee0dd43-f7bf-4035-8c37-cf8ea49f5d1e_45', '02d5e4b5-71a8-4469-b5ed-ae22055443ed_25', 'cf7e712c-aaf6-404f-bea5-cea214548c92_37', 'a70e725a-3c7e-45b6-b602-85d48f6752e8_44', '6d56d91c-f1b1-46c6-9456-e07d1dbbeb55_35', 'fc4f23c7-ba2e-4d9f-afca-32f15e47ef92_19', 'bf74ed2d-889b-49df-a023-dc4ce6a346f3_16', '6d8c9de4-65e5-4b5a-a1ed-d63de485099b_33', '279bdfb0-9dce-457b-adf0-621c4da187ac_71', 'fb5606be-9917-424e-83c8-192dd05ce959_15', '7535f4ff-8469-41ad-8f93-9d59315db900_21', '13683720-d092-4f6f-a438-75701f4ddfb3_31', '1c29b7e7-f7d3-4b90-b6a1-94347b9ac91a_33', '9b212da8-6dba-4684-995e-16f7d4eaa95e_100', '43effa66-0aea-46ca-be77-a3498395cbee_116', '279bdfb0-9dce-457b-adf0-621c4da187ac_65', '8e68ee6f-f53e-4003-8a1d-e0eed5797a8f_10', '99861853-4c7d-4e48-b146-688c5d16b929_28', '1a2592aa-f26b-4159-9afb-e58040de5d0c_11', '413ea6df-0042-4502-8e5b-4c2de084bf50_19', '515486af-f327-47ca-a1fc-28549f913e47_15', '9b212da8-6dba-4684-995e-16f7d4eaa95e_43', 'a49f4840-a0a1-438d-b474-9a471f55753c_112', '5eed19de-ab08-4015-980d-8e75fe411094_106', 'f4862bca-5a5a-435c-a791-08a0c79b7b08_60', 'b497d0a0-0d14-4c67-8f01-e1aa91e5cbd0_15', '6590d652-42b7-4b10-a08b-37ac378facbf_18', '191729c0-bf2c-4daf-8cb0-f600eec7a17a_17', '339ee84b-6c34-4358-9bd7-b7020cb409a5_36', '1b7b9187-91ac-4ded-86ca-be93043ab5ab_21', '1e0f4f35-c83d-4287-96c6-6de2f5841099_45', '5777b466-b52f-499f-bc8a-2fd0ba33cad9_62', '6e8b9a4b-b7fb-4487-b686-94a325d330d2_56', 'bbc51aad-3e80-48e8-8338-ee1828ede7b9_14', 'b79c7f48-54b4-4e8d-bc75-7b94a8250d7d_25', '85f21d37-73c8-42e8-bdda-1ff89dd6eb15_10', 'a5a9f54a-6b94-4711-867a-76ea90cd3008_7', 'f5916f54-5690-48b8-891b-2a1ba7e73b1a_19', '6db5b987-3c95-4751-92a2-1437c3539b38_37', '1c29b7e7-f7d3-4b90-b6a1-94347b9ac91a_25', 'b497d0a0-0d14-4c67-8f01-e1aa91e5cbd0_16', 'cd0326e0-1025-4596-aec1-8b08b91e732e_13', '6db5b987-3c95-4751-92a2-1437c3539b38_39', '85f21d37-73c8-42e8-bdda-1ff89dd6eb15_21', '6e8b9a4b-b7fb-4487-b686-94a325d330d2_26', 'f9c2847e-2bfa-4f73-ac25-e4ef68c8fbda_52', '9b212da8-6dba-4684-995e-16f7d4eaa95e_175', 'ae54c452-e7b3-4c7f-a056-7e95f42cad05_41', '4214e748-52e3-423e-bdbf-7a9150641e59_76', 'e9200dc7-ef75-4f30-ae23-bae236853994_12', 'b039d40f-d281-455f-83af-b0b9f801e3ad_11', 'bf74ed2d-889b-49df-a023-dc4ce6a346f3_10', 'b79c7f48-54b4-4e8d-bc75-7b94a8250d7d_7', '0d543b21-24a7-4cea-bfa8-74462a968cb0_20', '37773c5d-3cb1-42ee-bc6e-5e61675eb2bb_37'}
```

**Comment by Tushar-N** [comment]
@takfate The distributed sampler likes to throw away instances when it can't evenly split them among GPUs. Running inference with `batch_size = 1` per GPU will avoid this. i.e., `NUM_GPUS 8 TRAIN.BATCH_SIZE 8 TEST.BATCH_SIZE 8`

**Comment by takfate** [comment]
> @takfate The distributed sampler likes to throw away instances when it can't evenly split them among GPUs. Running inference with `batch_size = 1` per GPU will avoid this. i.e., `NUM_GPUS 8 TRAIN.BATCH_SIZE 8 TEST.BATCH_SIZE 8`

Thank you.

**Comment by takfate** [comment]
@Tushar-N 
hi,
I have one other problem.
There is an overlap between adjacent clips in the annotations.
It means that the end part of observable clips includes some information from the start part of the forecasting clips.
Does this also mean that when I predict 20 clips, I can use all the information up to the end time of the previous clip?

**Comment by Tushar-N** [comment]
Yes, that's how the benchmark is defined. The actions are sorted based on PNR timestamps and predictions happen over a much longer horizon (20 actions) so it's ok. If the input is `clips[0:i-1]`, the predictions are for actions in `clips[i:i+20]`

**Comment by takfate** [comment]
@Tushar-N 
So,
How should I forecast the first action clip(idx=0)?

**Comment by takfate** [comment]
> @Tushar-N So, How should I forecast the first action clip(idx=0)?

Ok.
I find your code passes the len(clips)<20+2.
Thank you.
