### ISSUE TITLE
Issues on a video loader for future hand prediction

### ISSUE THREAD

**Issue by sunilhoho** [EGO4D/forecasting#9]
Hi,

I've tried to implement baseline code for future hand prediction using this command,
```shell
 python tools/run_net.py --cfg /path/to/ego4d-hand_ant/configs/Ego4D/I3D_8x8_R50.yaml OUTPUT_DIR /path/to/ego4d-hand_ant/output/
```

Before running, I renamed 'fho_hands_train.json' to 'train.json', because of these lines.
https://github.com/EGO4D/forecasting/blob/c232d5f2e36dde029b37f6a3e17b992166fa39b7/Ego4D-Future-Hand-Prediction/slowfast/datasets/ego4dhand.py#L82-L84

However, it faces errors, and I think it is because the structure of annotations files doesn't match with the baseline code.
For example,
https://github.com/EGO4D/forecasting/blob/c232d5f2e36dde029b37f6a3e17b992166fa39b7/Ego4D-Future-Hand-Prediction/slowfast/datasets/ego4dhand.py#L97 clip_id and hand_dicts returns 'version' and '1' respectively.

If I am missing something, please let me know.

Thanks.

**Comment by Marchetz** [comment]
I have the same problem and I did the same procedure. Have you solved somehow? thanks!

**Comment by sunilhoho** [comment]
I haven't solved my issues. I'm just waiting for help.

**Comment by antoninofurnari** [comment]
Thank you both for opening and commenting on this issue and apologies if there has been no reply yet. Maybe @VJWQ can help?

**Comment by VJWQ** [comment]
Hi @sunilhoho @Marchetz we've fixed our dataloader, no need to rename the test file anymore, please update both the code base and the fho_hand_*.json files to run the code!
